### ISSUE TITLE
安装后，一直无法加载出 Cat button

### ISSUE THREAD

**Issue by Sunsh4j** [prinsss/twitter-web-exporter#12]
操作系统版本：Windows 10 LTSC 1809
浏览器版本：Thorium  115.0.5790.172
脚本管理器扩展版本：篡改猴 5.1.0

**Comment by prinsss** [comment]
在页面上按 F12 打开开发者工具，看下控制台 (Console) 中是否有错误输出，有的话把内容贴上来我看看。不确定的话也可以整个截图上传。

**Comment by prinsss** [comment]
上面的链接现在好像看不到了，是设置了过期时间吗？麻烦重新上传一下。

另外可以尝试按照这里的方法，设置一下 Tampermonkey 中 CSP 相关的选项，看下能否解决：https://github.com/prinsss/twitter-web-exporter/issues/8#issuecomment-2041523918

**Comment by prinsss** [comment]
奇怪，我看日志里面脚本都已经初始化并且在处理数据了，请尝试关闭广告屏蔽插件（如有）：

```
[twitter-web-exporter] App options loaded Object
[twitter-web-exporter] Hooked into XMLHttpRequest
[twitter-web-exporter] UserMedia: 12 items received
[twitter-web-exporter] UserTweets: 21 items received
```

如果还是不行，尝试在控制台中运行以下命令：

```js
localStorage.setItem('twitter-web-exporter', localStorage.getItem('twitter-web-exporter').replaceAll('false', 'true'))
```

然后刷新页面查看面板是否打开。

如果还是不行，再运行以下命令，看看是否有类似截图中的结果：

```js
document.getElementById('twe-root')
```

![CleanShot 2024-04-08 at 10 06 45](https://github.com/prinsss/twitter-web-exporter/assets/11206497/7965b107-4d59-4cd3-8e17-dae86fe543f7)

**Comment by prinsss** [comment]
好神奇的问题……试试按照以下步骤操作：

![CleanShot 2024-04-08 at 12 16 03](https://github.com/prinsss/twitter-web-exporter/assets/11206497/8ace141a-b714-4ba3-af07-a88010e0aa96)

另外可以试下用命令打开面板后，在 Settings 中换个主题，不知道会不会是和背景融为一体了。

**Comment by prinsss** [comment]
哈哈哈，还在社畜，身不由己😹

你先试试，还不行的话我晚点再看看

**Comment by prinsss** [comment]
不是这里搜索，先切换到 Elements 选项卡再搜索

**Comment by prinsss** [comment]
> 我发现了，只有在黑色主题时，cat才会显示，所有的浅色主题下均不会显示........ 当热，只是不显示，但是只要移到那个位置点击，是可以唤出面板的

你是不是手动切换过 Twitter 的深色模式？正常来说脚本界面的深色/浅色是根据系统设置来的，浅色主题需要搭配 Twitter 的浅色模式使用，反之亦然，不然可能就会出现按钮难以分辨的问题（深色按钮和深色背景融为一体了）。

后续我看看能不能提高下按钮的辨识度吧……😂

**Comment by prinsss** [comment]
> Twitter的深色模式不都是手动选择才会显示的吗？

设置成 Default 的话，是会根据系统设置来切换深色/浅色的。

那就先这样啦，有其他问题欢迎再反馈。:)
