### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by A518Z** [prinsss/twitter-web-exporter#13]
如果书签标注的是中文内容，导出CSV后，中文都是乱码，有解决的方法吗？

**Comment by prinsss** [comment]
Hi，你是用什么软件打开 CSV 显示乱码的呢？

请尝试使用 VS Code 等文本编辑器打开 CSV 文件，并选择以 UTF-8 编码打开，看看还会不会有中文乱码。

**Comment by A518Z** [comment]
用excel和系统自带的写字板打开都是乱码

**Comment by prinsss** [comment]
你说的这些软件对 UTF-8 的支持都有问题。请搜索关键字：excel csv 乱码 utf-8

尝试安装 VS Code 编辑器并用它打开，应该是不会乱码的：
https://code.visualstudio.com

**Comment by prinsss** [comment]
不好意思，我忽略了 Windows Excel 需要 BOM 文件头才能正确显示 UTF-8 编码 CSV 的问题。

这个问题后续会在 https://github.com/prinsss/twitter-web-exporter/pull/16 中修复。

**Comment by A518Z** [comment]
好的，谢谢

**Comment by prinsss** [comment]
此问题已在 [v1.0.10](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.0.10) 版本中修复，感谢 @mundane799699
