### ISSUE TITLE
需求：增加收集持久化功能，解决耗时过长网页崩溃数据丢失问题。

### ISSUE THREAD

**Issue by LYZ10** [prinsss/twitter-web-exporter#14]
你好，书签收藏推文过多时，容易出现网页崩溃问题，这样会浪费大量的时间及重复操作，希望可以增加持续收集或者间接保存功能来规避这个问题，使得在使用时能够更高效。非常感谢您开发这个这么有帮助的插件，祝一切都好。
问题截图：
![image](https://github.com/prinsss/twitter-web-exporter/assets/64691532/5ab28b66-ba43-480c-91ae-23cacaee09ff)
不知道数据达到多少条会奔溃，测试过一般在1000条后，网页奔溃后网页刷新又会回到第一条，出现这个后人也会很奔溃，哈哈哈。真的很想一次性就把书签导出干净，辛苦你啦，谢谢！

**Comment by bxb100** [comment]
有没人弄，没人弄我想弄弄

**Comment by prinsss** [comment]
@bxb100 我目前打算使用 IndexedDB 做持久化（类似本项目前身 [export-twitter-following-list](https://github.com/prinsss/export-twitter-following-list/blob/master/export-twitter-following-list.user.js#L541)），不过这会涉及到一些底层变更，咱们可以交流下。如果你也有兴趣，欢迎一起完善！

主要的变更点：

1. 需要在 `Interceptor` 中把所有抓取到的数据保存到 IDB 中（按模块分表）。
2. 把现在的 global store `Signal` 改成数据库中的行数（有新增时，需要响应式更新 UI）。
3. 提供清除数据库和导出数据库的选项。
4. 注意数据存入 IDB 后不要继续持有引用，防止上述的内存占用无限膨胀问题。
5. 最重要也是最麻烦的一点，需要把 TanStack Table 改造成 [server-side pagination](https://tanstack.com/table/latest/docs/guide/pagination#manual-server-side-pagination)/filtering/ordering。

因为目前所有数据都是塞在内存里的，所以直接全量前端分页处理分页展示就行了。如果改成 IDB 存储，就需要改造一下表格预览中的分页、搜索、排序方法。

**Comment by bxb100** [comment]
@prinsss 我也是打算用 indexedDB 来做（刚学 =。= 所以没细看你说的 edge case）

**Comment by JunkoJk** [comment]
Hi，谢谢大佬制作工具，这边尝试导出总3k+的账号推文，也是1k左右就卡住报错了，重新加载也没有用，找过来发现已经有类似问题（虽然是书签），于是想补充一下例子👇再次感谢，期待优化，谢谢！
![image](https://github.com/prinsss/twitter-web-exporter/assets/111702403/e4793b38-26db-4103-a293-8149b339f700)

**Comment by prinsss** [comment]
@LYZ10 @JunkoJk 

可以试试我刚发的 [1.2.0-alpha.1](https://github.com/prinsss/twitter-web-exporter/releases/tag/nightly) 测试版，新增支持了本地数据库持久化，现在即使刷新页面也不会丢失已抓取到的数据了。我自测下来加载 1000 条数据，内存占用没有明显波动。

不过表格预览界面的分页还没时间做，点击预览按钮后会吃一波内存……应该不至于会崩溃，如果有问题继续反馈吧。

---

@bxb100 我目前正在 [idb](https://github.com/prinsss/twitter-web-exporter/commits/idb/) 分支上开发。

**Comment by prinsss** [comment]
> Hi，谢谢大佬制作工具，这边尝试导出总3k+的账号推文，也是1k左右就卡住报错了，重新加载也没有用，找过来发现已经有类似问题（虽然是书签），于是想补充一下例子👇再次感谢，期待优化，谢谢！

从你这图中的报错看，有可能是另外的问题。可以参考一下 https://github.com/prinsss/twitter-web-exporter/issues/1 中的排查方法，提供具体的错误日志方便定位问题。

**Comment by LYZ10** [comment]
> @LYZ10 @JunkoJk
> 
> 可以试试我刚发的 [1.2.0-alpha.1](https://github.com/prinsss/twitter-web-exporter/releases/tag/nightly) 测试版，新增支持了本地数据库持久化，现在即使刷新页面也不会丢失已抓取到的数据了。我自测下来加载 1000 条数据，内存占用没有明显波动。可以试试我刚发的 1.2.0-alpha.1 测试版，新增支持了本地数据库持久化，现在即使刷新页面也不会丢失已抓取到的数据了。 我自测下来加载 1000 条数据，内存占用没有明显波动。
> 
> 不过表格预览界面的分页还没时间做，点击预览按钮后会吃一波内存……应该不至于会崩溃，如果有问题继续反馈吧。不过表格预览界面的分页还没时间做，点击预览按钮后会吃一波内存…… 应该不至于会崩溃，如果有问题继续反馈吧。
> 
> @bxb100 我目前正在 [idb](https://github.com/prinsss/twitter-web-exporter/commits/idb/) 分支上开发。

收到收到，我试试哈。

**Comment by JunkoJk** [comment]
> > Hi，谢谢大佬制作工具，这边尝试导出总3k+的账号推文，也是1k左右就卡住报错了，重新加载也没有用，找过来发现已经有类似问题（虽然是书签），于是想补充一下例子👇再次感谢，期待优化，谢谢！
> 
> 从你这图中的报错看，有可能是另外的问题。可以参考一下 #1 中的排查方法，提供具体的错误日志方便定位问题。

尝试了新版，很神奇的是直接读取还是会卡在1000左右，于是想开着控制台看是哪里出错，结果顺顺利利划完了3k+，再次感谢！

**Comment by prinsss** [comment]
> 尝试了新版，很神奇的是直接读取还是会卡在1000左右，于是想开着控制台看是哪里出错，结果顺顺利利划完了3k+，再次感谢！

哈哈哈😂，那你有时间可以试试开着控制台刷 1000 条，看看还会不会报错。如果这是一个共性问题，那我可以一起修复掉，如果不能复现那就算啦。

**Comment by abm1224** [comment]
作者你好，我想导出全部推文，大概5000条，向下滚动到800时就拖不动了，下面是空白的，刷新后也是如此，请问这是推特的问题吗？有没有解决办法呢？
![image](https://github.com/user-attachments/assets/1c03acab-b813-4a86-be30-08651db25383)

**Comment by prinsss** [comment]
> 作者你好，我想导出全部推文，大概5000条，向下滚动到800时就拖不动了，下面是空白的，刷新后也是如此，请问这是推特的问题吗？有没有解决办法呢？

Hi，你可以尝试禁用 Tampermonkey 脚本，或者换个浏览器登录试试，然后看看能加载出来多少条。如果还是只有 800 条，可以换个其他用户导出试试。如果还是不行，那说明这可能是 Twitter 的限制，脚本方面就无能为力了。

**Comment by qingchunnh** [comment]
> 作者你好，我想导出全部推文，大概5000条，向下滚动到800时就拖不动了，下面是空白的，刷新后也是如此，请问这是推特的问题吗？有没有解决办法呢？ ![image](https://private-user-images.githubusercontent.com/85410859/356821505-1c03acab-b813-4a86-be30-08651db25383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTQwMjksIm5iZiI6MTcyODM5MzcyOSwicGF0aCI6Ii84NTQxMDg1OS8zNTY4MjE1MDUtMWMwM2FjYWItYjgxMy00YTg2LWJlMzAtMDg2NTFkYjI1MzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEzMjIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZTM5NGVmMDM1NjE1Y2E5MDA5MmRhZTVkNmMzMzgyZTcyZjQ4ZmVjOTliMmZiODg2N2VkOGY0MWNhZjQ3NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2giAEufrBNossVN0zITzeDwWTYEYlxGXDVkc1q6h43o)

我想我知道原因了，马斯克说过未认证的账号只能看到800条信息，认证的账号可以看到8000条

**Comment by abm1224** [comment]
> > 作者你好，我想导出全部推文，大概5000条，向下滚动到800时就拖不动了，下面是空白的，刷新后也是如此，请问这是推特的问题吗？有没有解决办法呢？ ![image](https://private-user-images.githubusercontent.com/85410859/356821505-1c03acab-b813-4a86-be30-08651db25383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTQwMjksIm5iZiI6MTcyODM5MzcyOSwicGF0aCI6Ii84NTQxMDg1OS8zNTY4MjE1MDUtMWMwM2FjYWItYjgxMy00YTg2LWJlMzAtMDg2NTFkYjI1MzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEzMjIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZTM5NGVmMDM1NjE1Y2E5MDA5MmRhZTVkNmMzMzgyZTcyZjQ4ZmVjOTliMmZiODg2N2VkOGY0MWNhZjQ3NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2giAEufrBNossVN0zITzeDwWTYEYlxGXDVkc1q6h43o)
> 
> 我想我知道原因了，马斯克说过未认证的账号只能看到800条信息，认证的账号可以看到8000条

感谢解答！马斯克该死啊 后来想到个办法是用搜索限定日期，可以尝试刷出以前的推

**Comment by qingchunnh** [comment]
> > > 作者你好，我想导出全部推文，大概5000条，向下滚动到800时就拖不动了，下面是空白的，刷新后也是如此，请问这是推特的问题吗？有没有解决办法呢？ ![image](https://private-user-images.githubusercontent.com/85410859/356821505-1c03acab-b813-4a86-be30-08651db25383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTQwMjksIm5iZiI6MTcyODM5MzcyOSwicGF0aCI6Ii84NTQxMDg1OS8zNTY4MjE1MDUtMWMwM2FjYWItYjgxMy00YTg2LWJlMzAtMDg2NTFkYjI1MzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEzMjIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZTM5NGVmMDM1NjE1Y2E5MDA5MmRhZTVkNmMzMzgyZTcyZjQ4ZmVjOTliMmZiODg2N2VkOGY0MWNhZjQ3NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2giAEufrBNossVN0zITzeDwWTYEYlxGXDVkc1q6h43o)
> > 
> > 
> > 我想我知道原因了，马斯克说过未认证的账号只能看到800条信息，认证的账号可以看到8000条
> 
> 感谢解答！马斯克该死啊 后来想到个办法是用搜索限定日期，可以尝试刷出以前的推

谢谢你分享的办法，我也还在想怎么办呢差点开了蓝标

**Comment by prinsss** [comment]
[v1.2.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.2.0) 版本已正式发布，支持持久化至浏览器本地数据库。如有问题，欢迎创建新 issue 反馈。:)

![CleanShot 2024-10-22 at 19 41 07](https://github.com/user-attachments/assets/0c2ad1a8-e0de-4293-a19a-7ef69c5e3742)
