### ISSUE TITLE
能在浏览timeline时也捕获数据么? 

### ISSUE THREAD

**Issue by hardway** [prinsss/twitter-web-exporter#15]

**Comment by prinsss** [comment]
是说首页的为你推荐和正在关注吗？可以，下个版本吧。

**Comment by hardway** [comment]
是的，也包括浏览自己的列表。非常期待

**Comment by prinsss** [comment]
[v1.1.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.1.0) 已更新，支持导出主页时间线与列表时间线的推文。

这两个新模块默认是禁用的，请在设置页面中启用。如果使用中有发现问题，欢迎反馈。:)
