### ISSUE TITLE
请求适配中文

### ISSUE THREAD

**Issue by windy1021** [prinsss/twitter-web-exporter#17]

**Comment by prinsss** [comment]
中文版已更新，支持在设置页面中切换语言，可以在这里体验：
https://github.com/prinsss/twitter-web-exporter/releases/tag/nightly

中文使用文档：
https://github.com/prinsss/twitter-web-exporter/blob/main/docs/README.zh-Hans.md

**Comment by windy1021** [comment]
> 中文版已更新，支持在设置页面中切换语言，可以在这里体验： https://github.com/prinsss/twitter-web-exporter/releases/tag/nightly
> 
> 中文使用文档： https://github.com/prinsss/twitter-web-exporter/blob/main/docs/README.zh-Hans.md

非常感谢！！！
