### ISSUE TITLE
建议上架到Greasy Fork

### ISSUE THREAD

**Issue by mundane799699** [prinsss/twitter-web-exporter#18]
在[Greasy Fork](https://greasyfork.org/zh-CN)没搜到这个脚本，是没上架吗？
这么好的脚本不上架可惜了

**Comment by prinsss** [comment]
哈哈，之前主要是懒……😂

已上架：
https://greasyfork.org/zh-CN/scripts/492218-twitter-web-exporter

不过主要分发平台还是会在 GitHub，管理起来方便点。
