### ISSUE TITLE
No export button

### ISSUE THREAD

**Issue by LuckDIY** [prinsss/twitter-web-exporter#2]
<img width="856" alt="image" src="https://github.com/prinsss/twitter-web-exporter/assets/49643408/7914b909-e174-492b-bdd0-8cee06391f6f">

**Comment by prinsss** [comment]
Hi,

The export button is placed under the pagination component. It could be hidden from visible area on some screen sizes. (should be considered as an responsiveness issue though)

Please move your cursor and hover on the "Rows per page" text, then scroll down with your mouse wheel or trackpad. Or simply enlarge your browser vertically and the buttons then should show up.

**Comment by LuckDIY** [comment]
@prinsss It's caused by the screen size. It works. Thank you very much.
