### ISSUE TITLE
Feature request: import

### ISSUE THREAD

**Issue by URenko** [prinsss/twitter-web-exporter#20]
It would be nice if the metadata exported by this user script could be imported back into likes/bookmarks.
This will be helpful for migrating between accounts or migrating between likes and bookmarks.

**Comment by prinsss** [comment]
Thank you for your suggestion. 

Unfortunately, importing from exported data _back_ to Twitter requires actively invoking Twitter's private APIs, which is something that we try to avoid for the sake of security.

The script is designed to export data from Twitter only. You can use the exported data for your own purpose, such as data analysis, data visualization, or data archival.

Maybe you can try to use something like [Selenium](https://www.selenium.dev/) to automate the process of importing data back to Twitter. For example, write a script to read from exported JSON data and then simulate the process of accessing a tweet and clicking the "Like/Bookmark" button.

**Comment by prinsss** [comment]
Closing as not planned for now. Feel free to open a new issue if you have any further questions. :)
