### ISSUE TITLE
Export chat history from user

### ISSUE THREAD

**Issue by nikitavoloboev** [prinsss/twitter-web-exporter#21]

**Comment by prinsss** [comment]
This feature could be implemented by adding a module intercepting following API requests:

```
https://twitter.com/i/api/1.1/dm/user_updates.json
https://twitter.com/i/api/1.1/dm/conversation/{uid}-{uid}.json
```

It seems that Direct Messages are still using the legacy v1.1 API and extra works may be required to support that. Will have a look into it if I have time later.

**Comment by prinsss** [comment]
Exporting direct messages is supported now in [nightly builds](https://github.com/prinsss/twitter-web-exporter/releases/tag/nightly). Feedback is welcome. :)
