### ISSUE TITLE
[Function Request]导出用户数据

### ISSUE THREAD

**Issue by qingchunnh** [prinsss/twitter-web-exporter#22]
导出头像、名称、简介，注册时间，地区等，可选导出关注和关注者等
如果可以的话那真是太好了,你可以随便关闭此issues

**Comment by prinsss** [comment]
Hi，你提到的功能基本都已经支持了，具体请查看[文档](https://github.com/prinsss/twitter-web-exporter/blob/main/docs/README.zh-Hans.md)。

需要注意的是目前用户资料的导出默认不包含「位置」。如果确实需要，请在导出时勾选「包括所有元数据」选项，然后在 `legacy.location` 中可以查看用户填写的位置。

**Comment by qingchunnh** [comment]
> Hi，你提到的功能基本都已经支持了，具体请查看[文档](https://github.com/prinsss/twitter-web-exporter/blob/main/docs/README.zh-Hans.md)。
> 
> 需要注意的是目前用户资料的导出默认不包含「位置」。如果确实需要，请在导出时勾选「包括所有元数据」选项，然后在 `legacy.location` 中可以查看用户填写的位置。

抱歉，是我的问题，但是好像没有单独保存用户元数据的选项，只能连带着推文一起保存？

**Comment by prinsss** [comment]
此脚本的模块分为用户模块和推文模块两大类。

在通过以下模块导出时，导出的是**用户数据**。此时勾选「包括所有元数据」可以同时保存用户位置信息，点击「导出媒体文件」可以下载用户头像和横幅图片：

- 关注者
- 正在关注
- 列表成员
- 列表关注者

因此，如果你希望批量下载用户头像，目前只能在这些模块中下载。

---

在通过其他模块导出时，导出的是**推文数据**，以及部分用户数据（如用户昵称、用户名等）。此时勾选「包括所有元数据」可以同时保存所有的用户信息，包括位置信息。点击「导出媒体文件」，可以下载推文中包含的图片或视频：

- 主页时间线
- 列表时间线
- 书签
- 喜欢
- 用户推文
- 用户媒体
- 推文详情
- 搜索结果

P.S. 点击用户头像打开的预览弹窗，右键另存为保存的也是原图。

**Comment by qingchunnh** [comment]
> 此脚本的模块分为用户模块和推文模块两大类。
> 
> 在通过以下模块导出时，导出的是**用户数据**。此时勾选「包括所有元数据」可以同时保存用户位置信息，点击「导出媒体文件」可以下载用户头像和横幅图片：
> 
> * 关注者
> * 正在关注
> * 列表成员
> * 列表关注者
> 
> 因此，如果你希望批量下载用户头像，目前只能在这些模块中下载。
> 
> 在通过其他模块导出时，导出的是**推文数据**，以及部分用户数据（如用户昵称、用户名等）。此时勾选「包括所有元数据」可以同时保存所有的用户信息，包括位置信息。点击「导出媒体文件」，可以下载推文中包含的图片或视频：
> 
> * 主页时间线
> * 列表时间线
> * 书签
> * 喜欢
> * 用户推文
> * 用户媒体
> * 推文详情
> * 搜索结果
> 
> P.S. 点击用户头像打开的预览弹窗，右键另存为保存的也是原图。

但是好像不可以直接导出当前访问账号的个人数据，就像在关注列表里下载其他人那样，我可以在别人的关注列表里导出他，但是不可以直接在他的主页导出他的个人数据，不过可以通过自己关注对方从自己的关注列表里导出

**Comment by qingchunnh** [comment]
我还发现在今天我使用用户推文功能的时候出现了
`出错了。
错误: Cannot read properties of undefined (reading 'replace')`
很抱歉打扰您这么久！

**Comment by prinsss** [comment]
> 但是好像不可以直接导出当前访问账号的个人数据。就像在关注列表里导出其他人那样，我可以在别人的关注列表里导出他，但是不可以直接在他的主页导出他的个人数据，不过可以通过自己关注对方从自己的关注列表里导出

是的，目前不支持在直接访问用户主页时导出这个人的用户数据（只能导出推文），后续可以考虑支持一下。

> 我还发现在今天我使用用户推文功能的时候出现了 `出错了。 错误: Cannot read properties of undefined (reading 'replace')` 很抱歉打扰您这么久！

麻烦按照 https://github.com/prinsss/twitter-web-exporter/issues/1 中的排查方法，打开浏览器控制台，把详细的错误信息发上来，以便我定位问题。

**Comment by qingchunnh** [comment]
> > 但是好像不可以直接导出当前访问账号的个人数据。就像在关注列表里导出其他人那样，我可以在别人的关注列表里导出他，但是不可以直接在他的主页导出他的个人数据，不过可以通过自己关注对方从自己的关注列表里导出
> 
> 是的，目前不支持在直接访问用户主页时导出这个人的用户数据（只能导出推文），后续可以考虑支持一下。
> 
> > 我还发现在今天我使用用户推文功能的时候出现了 `出错了。 错误: Cannot read properties of undefined (reading 'replace')` 很抱歉打扰您这么久！
> 
> 麻烦按照 #1 中的排查方法，打开浏览器控制台，把详细的错误信息发上来，以便我定位问题。

好的谢谢，报错的问题就出现了那么一次，后来第二天用的时候已经不会报错了

**Comment by qingchunnh** [comment]
我发现了一个新问题，当我的列表里只有一个人时，导出媒体会没有选项，如果是2个人的情况下只会漏出上半部分
![Snipaste_2024-05-02_13-06-13](https://github.com/prinsss/twitter-web-exporter/assets/96961592/4f3a79f0-a86b-4687-9eec-852b63b9e90d)

**Comment by qingchunnh** [comment]
> 我发现了一个新问题，当我的列表里只有一个人时，导出媒体会没有选项，如果是2个人的情况下只会漏出上半部分 ![Snipaste_2024-05-02_13-06-13](https://private-user-images.githubusercontent.com/96961592/327317538-4f3a79f0-a86b-4687-9eec-852b63b9e90d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODQxOTgsIm5iZiI6MTcxNTY4Mzg5OCwicGF0aCI6Ii85Njk2MTU5Mi8zMjczMTc1MzgtNGYzYTc5ZjAtYTg2Yi00Njg3LTllZWMtODUyYjYzYjllOTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEwNTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwY2ZjY2RiZTFkZjlhZTdhYWM5MTY3NjIwMTBhNDc3YmZmMzEzOGEwM2JkMjkzNGVjNWQxNzAzNGE1M2MyYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A38MWNJtBKAapOKApEPactlWPmrsCkNfHeMJ8H4MDQM)

@prinsss 不管是推文还是关注还是其他什么，只要列表里是一个的时候就会这样

**Comment by prinsss** [comment]
> 我发现了一个新问题，当我的列表里只有一个人时，导出媒体会没有选项，如果是2个人的情况下只会漏出上半部分 !

试试这个版本，应该修复了：

https://github.com/prinsss/twitter-web-exporter/releases/download/nightly/twitter-web-exporter.user.js

**Comment by prinsss** [comment]
此问题已在 [v1.2.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.2.0) 版本中修复。如有问题，欢迎继续反馈。:)

**Comment by qingchunnh** [comment]
> 此问题已在 [v1.2.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.2.0) 版本中修复。如有问题，欢迎继续反馈。:)

请问是否还有计划增加在当前用户页面导出用户信息，像导出正在关注那样，因为我想导出我自己，我目前的方法还是登录其他账号到导出，比较麻烦

**Comment by qingchunnh** [comment]
> 此问题已在 [v1.2.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.2.0) 版本中修复。如有问题，欢迎继续反馈。:)

还有个问题就是脚本支持MV3嘛，今天油猴不知道怎么了给我自动更新到5.3.1了，修改内容安全策略（CSP）头信息 这个选项已经没有yes的选项了 :(

**Comment by prinsss** [comment]
@qingchunnh 支持的，MV3 主要是浏览器扩展要考虑的事情，和脚本没什么关系。

我目前在 Chrome 130 + Tampermonkey 5.3.1，以及 Firefox 115 + Violentmonkey 2.26.0 上测试都没问题。

**Comment by qingchunnh** [comment]
> > 在当前用户页面导出用户信息，像导出正在关注那样
> 
> @qingchunnh 已实现，可以安装 [测试版](https://github.com/prinsss/twitter-web-exporter/releases/download/nightly/twitter-web-exporter.user.js) 体验。

感谢作者大大\(‵▽′)/
