### ISSUE TITLE
[Function Request] Export media by type

### ISSUE THREAD

**Issue by universorum** [prinsss/twitter-web-exporter#28]
In export page, add the new option to allow user can choose the media type that want to export like:

( ) Include Video
(v) Include Image

**Comment by prinsss** [comment]
Media type filtering is now available in [nightly build](https://github.com/prinsss/twitter-web-exporter/releases/download/nightly/twitter-web-exporter.user.js).

![CleanShot 2024-10-24 at 00 45 24](https://github.com/user-attachments/assets/16a54ce6-bf7e-4a5d-bccf-66031e3f0669)
