### ISSUE TITLE
utils 中 xssFilter 函数可能会接收到 undefined 的 url

### ISSUE THREAD

**Issue by Chilfish** [prinsss/twitter-web-exporter#30]
在个人主页获取推文列表时，点导出会有 undefined 的报错，定位到是下面这个函数的问题

https://github.com/prinsss/twitter-web-exporter/blob/7b2307fa5503469329c39f9e9852fc7097019ecf/src/utils/common.ts#L104-L111

如下图，推特返回的数据中可能会漏掉某个字段(expaned_url)，导致对 undefined .replace，但这种情况及其少见，导了五六千条才出现一次……

![image](https://github.com/prinsss/twitter-web-exporter/assets/60336739/64c43fb6-e575-4655-9800-ec50da66c8ce)

感觉做个特判就行

```ts
export function xssFilter(str: string) {
  if (!str) return '#';
  return str.replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
```

**Comment by prinsss** [comment]
感谢你的反馈！这个问题将在下一个版本中修复。:)

**Comment by prinsss** [comment]
此问题已在最新测试版中修复，如有问题欢迎反馈。

https://github.com/prinsss/twitter-web-exporter/releases/download/nightly/twitter-web-exporter.user.js
