### ISSUE TITLE
导出关注列表 错误--Cannot read properties of undefined (reading 'screen_name')

### ISSUE THREAD

**Issue by qxy203** [prinsss/twitter-web-exporter#33]
#5 Following: 50 items received
#4 UserTweets: Failed to parse API response (Message: Cannot read properties of undefined (reading 'tweet_results'))
  This may be a problem caused by Twitter updates.
  Please file an issue on GitHub:
  https://github.com/prinsss/twitter-web-exporter/issues
#3 UserTweets: Failed to parse API response (Message: Cannot read properties of undefined (reading 'tweet_results'))
  This may be a problem caused by Twitter updates.
  Please file an issue on GitHub:
  https://github.com/prinsss/twitter-web-exporter/issues
#2 UserMedia: 0 items received
#1 Hooked into XMLHttpRequest
#0 App options loaded

**Comment by prinsss** [comment]
Hi，你可以试试最新的测试版，看看有没有解决问题：

https://github.com/prinsss/twitter-web-exporter/releases/download/nightly/twitter-web-exporter.user.js

**Comment by qxy203** [comment]
最新版本 没有报错的问题了 不过144的关注只查出143个 应该是把报错的那个删除了

**Comment by prinsss** [comment]
> 最新版本 没有报错的问题了 不过144的关注只查出143个 应该是把报错的那个删除了

看下日志窗口里有没有警告信息输出？有的话可以贴上来，大概率是那个账号被 Suspended 了。

**Comment by qxy203** [comment]
很玄学 我今天更新v1.2.0-alpha.3 发现怎么样刷新，都清除不了数据。然后退回了正式版1.1.0，居然又不报错了，没有发现bug了

**Comment by prinsss** [comment]
此问题已在 [v1.2.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.2.0) 版本中修复。如有问题，欢迎继续反馈。:)
