### ISSUE TITLE
查看自己的转推用户数量的时候报错

### ISSUE THREAD

**Issue by SemDLeo** [prinsss/twitter-web-exporter#34]
#10 SearchTimeline: Failed to parse API response (Message: Cannot read properties of undefined (reading 'entries'))
  This may be a problem caused by Twitter updates.
  Please file an issue on GitHub:
  https://github.com/prinsss/twitter-web-exporter/issues
#9 SearchTimeline: Failed to parse API response (Message: Cannot read properties of undefined (reading 'entries'))
  This may be a problem caused by Twitter updates.
  Please file an issue on GitHub:
  https://github.com/prinsss/twitter-web-exporter/issues

查看转推用户的时候报错。

**Comment by prinsss** [comment]
Hi,

可以详细描述一下什么是「查看自己的转推用户数量」吗？还有其他的错误日志吗？最好可以附上截图方便排查问题，谢谢。

**Comment by SemDLeo** [comment]
> Hi,
> 
> 可以详细描述一下什么是「查看自己的转推用户数量」吗？还有其他的错误日志吗？最好可以附上截图方便排查问题，谢谢。

![image](https://github.com/prinsss/twitter-web-exporter/assets/136533034/1f7e4888-f33f-4fa2-a82f-5d803a8e3b61)
![image](https://github.com/prinsss/twitter-web-exporter/assets/136533034/aef6d004-28ac-4a18-93d4-e2954a881da2)
#7 SearchTimeline: Failed to parse API response (Message: Cannot read properties of undefined (reading 'entries'))
  This may be a problem caused by Twitter updates.
  Please file an issue on GitHub:
  https://github.com/prinsss/twitter-web-exporter/issues
#6 SearchTimeline: Failed to parse API response (Message: Cannot read properties of undefined (reading 'entries'))
  This may be a problem caused by Twitter updates.
  Please file an issue on GitHub:
  https://github.com/prinsss/twitter-web-exporter/issues
#5 SearchTimeline: Failed to parse API response (Message: Cannot read properties of undefined (reading 'entries'))
  This may be a problem caused by Twitter updates.
  Please file an issue on GitHub:
  
  点击 View post engagements之后， Quotes[引用转发]的数据可以呈现。  查看Reposts[转推]数据的时候，日志上会报出上方的错误

**Comment by prinsss** [comment]
此问题应该已在最新测试版中修复，如有问题欢迎反馈。

https://github.com/prinsss/twitter-web-exporter/releases/download/nightly/twitter-web-exporter.user.js

**Comment by prinsss** [comment]
此问题已在 [v1.2.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.2.0) 版本中修复。如有问题，欢迎继续反馈。:)
