### ISSUE TITLE
Does this work with suspended accounts

### ISSUE THREAD

**Issue by CrimsonHellRider** [prinsss/twitter-web-exporter#35]
Hey. New to this whole scripting thing, so forgive me if any of this sounds basic. I downloaded this script to see if it would still work on suspended accounts so I could export booksmarks, followers and the like, and found that while the scripts side panel initially worked, after x'ing out of it I see no option to reopen it.  The 🐈 Cat mentioned on the download page is nowhere to be found and I am not knowledgeable enough on code to try and mess with it myself.

Am I SoL? Does the script just not work on suspended accounts? Or am I missing something obvious?

Once again, sorry if this sounds stupid or amateurish.

**Comment by prinsss** [comment]
Thank you for your feedback!

As this script is grabbing data from the webpage, it is possible to export data if only that data could be seen on Twitter Web App. When you logged in with a suspended account, can you browse your bookmarks, followers and likes on Twitter? If you can, the script will work. :)

About the problem of missing 🐈 Cat button, could you please provide more information about it?

- What browser and version are you using?
- What script manager are you using? (e.g. Tampermonkey, Violentmonkey)
- What version of the script are you using?
- Press F12 to open the developer tools, and then click on the Console tab. Are there any error messages?

Also, if you are browsing Twitter in dark mode, without setting the browser itself to use dark mode, the 🐈 Cat button may be hard to see. Try to change to light mode and see if it appears.

**Comment by CrimsonHellRider** [comment]
Switching to light mode did the trick! :) Switched the script to dark mode and now the cat is easier to see in Twitter's dark mode as well.

Was using Google Chrome Version 126.0.6478.127 with Tampermonkey
Twitter Web Exporter is Version 1.1.0

Unfortunately Twitter on Chrome (and mobile for that matter) just shows my followers/following/bookmarks/likes/etc. at 0 while suspended, and it seems to be that way for the web app as well. It seems to just be something that happens to suspended accounts from what I can find.

**Comment by prinsss** [comment]
Sorry to hear that. Unfortunately, the script is not able to export data if Twitter itself doesn't allow us to access it. :(

Feel free to ask if you have any further questions.
