### ISSUE TITLE
不起作用，看不到左侧小猫

### ISSUE THREAD

**Issue by JamesZlearner** [prinsss/twitter-web-exporter#37]

**Comment by prinsss** [comment]
Hi，

请提供以下信息方便排查问题：

1. 你的浏览器是什么，版本是多少
2. 你使用的脚本管理器版本（Tampermonkey、Violentmonkey）
3. 你使用的 twitter-web-exporter 版本
4. 你是否正在使用暗黑模式浏览网页？
5. 按 F12 打开浏览器控制台，是否有红色的报错信息？

**Comment by 18175613591** [comment]
我也看不见了
谷歌浏览器谷歌浏览器
版本 126.0.6478.127（正式版本） （64 位）
有红色的报错
开了暗黑
twitter-web-exporter 版本我是删除了重新又下载的
感谢您了

**Comment by JamesZlearner** [comment]
是暗黑模式下的显示错误，已经解决，感谢您的开发！

**Comment by prinsss** [comment]
Hi @18175613591 ,

你可以尝试把 Twitter 改成亮色模式，再看看按钮是否会出现。如果还是不出现，请将浏览器控制台上的红色报错截图，或者复制粘贴过来，以便排查具体问题。

**Comment by qxy203** [comment]
> 你好，
> 
> 请提供以下信息方便排查问题：
> 
> 1. 你的浏览器是什么，版本是多少
> 2. 你使用的脚本管理器版本（Tampermonkey、Violentmonkey）
> 3. 您使用的 twitter-web-exporter 版本
> 4. 你是否正在使用暗黑模式？
> 5. 按F12打开浏览器控制台，是否有红色的报错信息？

1.mac 系统Chrome 版本 126.0.6478.127（正式版本） (x86_64)
2.Tampermonkey
3.   1.1.0
4.否
5.否

**Comment by ianlai0318** [comment]
<img width="556" alt="截圖 2024-07-20 晚上11 03 05" src="https://github.com/user-attachments/assets/f6b4c68f-d20d-4c83-a748-607306a8592d">
我的也不起作用
1.mac 系统Chrome 版本 126.0.6478.127 (正式版本) (arm64)
2.Tampermonkey
3.1.1.0
4.否
5.是

**Comment by hjzzd** [comment]
![JM_`RS~(XMGMX 98YMYY~VS](https://github.com/user-attachments/assets/38e39de9-0ae8-40d5-b7cb-09348ccd3c82)
127.0.6533.73（正式版本） （64 位） 2.Tampermonkey 3.1.1.0 4.否 5.是

**Comment by prinsss** [comment]
Hi @ianlai0318 @hjzzd ,

你们提供的图片中的报错是其他报错，和 twitter-web-exporter 无关。你们也是遇到了看不到按钮的问题吗？

请尝试使用这个版本，看看是否还有问题：

https://github.com/prinsss/twitter-web-exporter/releases/download/nightly/twitter-web-exporter.user.js

**Comment by NoraItachi** [comment]
> Hi，
> 
> 请提供以下信息方便排查问题：
> 
> 1. 你的浏览器是什么，版本是多少
> 2. 你使用的脚本管理器版本（Tampermonkey、Violentmonkey）
> 3. 你使用的 twitter-web-exporter 版本
> 4. 你是否正在使用暗黑模式浏览网页？
> 5. 按 F12 打开浏览器控制台，是否有红色的报错信息？

1.版本 128.0.6613.138（正式版本） (x86_64)

**Comment by NoraItachi** [comment]
> Hi，
> 
> 请提供以下信息方便排查问题：
> 
> 1. 你的浏览器是什么，版本是多少
> 2. 你使用的脚本管理器版本（Tampermonkey、Violentmonkey）
> 3. 你使用的 twitter-web-exporter 版本
> 4. 你是否正在使用暗黑模式浏览网页？
> 5. 按 F12 打开浏览器控制台，是否有红色的报错信息？

1.版本 128.0.6613.138（正式版本） (x86_64)
2.Tampermonkey
3.       1.1.0
4. no
![截屏2024-10-18 16 51 43](https://github.com/user-attachments/assets/fe95944c-09b4-4636-b5aa-4c6ca734084f)

5. 
![截屏2024-10-18 16 51 43](https://github.com/user-attachments/assets/f0a18fbd-c895-435e-ab61-c6eb4d7e5b69)

**Comment by prinsss** [comment]
@NoraItachi 请尝试使用 [v1.2.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.2.0) 版本，此版本在菜单栏中新增了可以打开控制面板的菜单项。

如果更新后还是看不到菜单，请新开一个 issue 反馈。:)

![03-menu-commands](https://github.com/user-attachments/assets/aee2abc8-1b53-424b-97ff-b68ba1f57674)
