### ISSUE TITLE
v1.2.0-alpha.3 版刷新页面不能清除数据

### ISSUE THREAD

**Issue by warcns** [prinsss/twitter-web-exporter#38]
v1.2.0-alpha.3 版刷新页面不能清除已经获取的数据，需要去每一模块手动清除数据，请问这是不是bug啊

**Comment by qingchunnh** [comment]
> v1.2.0-alpha.3 版刷新页面不能清除已经获取的数据，需要去每一模块手动清除数据，请问这是不是bug啊

请查看 #14

**Comment by prinsss** [comment]
Hi,

> v1.2.0-alpha.3 版刷新页面不能清除已经获取的数据

这个不是 bug，是新版本的特性，主要就是为了防止因为页面崩溃而意外丢失数据。1.2.0 之后的版本数据是存在浏览器本地数据库中的，刷新页面不会清除。

如果需要点开预览页面，点击左下角的「清除」按钮。

**Comment by prinsss** [comment]
目前 UI 上的文案可能有些地方还没有调整，比如「刷新页面或清除数据以开始新的捕获」应该改为「清除数据以开始新的捕获」，这个后面会一起改掉的。:)

**Comment by warcns** [comment]
好的，我明白了，大佬的这个插件非常好用，非常感谢。

**Comment by prinsss** [comment]
谢谢夸赞～如果还有其他问题，欢迎继续反馈。:D
