### ISSUE TITLE
Uncaught (in promise) Error: Permission denied to access object

### ISSUE THREAD

**Issue by mone-stk** [prinsss/twitter-web-exporter#39]
![image](https://github.com/user-attachments/assets/667651f7-8998-44cf-b698-e22fe8d2bcee)
![image](https://github.com/user-attachments/assets/2b29069b-62cf-4e1c-b33a-f9d67a473096)

How to fix?

**Comment by mone-stk** [comment]
Browser: Firefox
User Script Manager: Tampermonkey
Web Exporter v1.1.0

**Comment by qingchunnh** [comment]
Maybe you could try [Nightly Build](https://github.com/prinsss/twitter-web-exporter/releases/tag/nightly)?

**Comment by mone-stk** [comment]
The results did not change.

`Uncaught (in promise) Error: Permission denied to access object
    open blob:https://x.com/3cb68114-b426-4c94-9cf6-2cd7eeab2f2e:408
    open blob:https://x.com/3cb68114-b426-4c94-9cf6-2cd7eeab2f2e:496
    open blob:https://x.com/3cb68114-b426-4c94-9cf6-2cd7eeab2f2e:584
    open blob:https://x.com/3cb68114-b426-4c94-9cf6-2cd7eeab2f2e:672
    i https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    errorFilter https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    yn https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    dn https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    Mn https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    zd https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    Xd https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    On https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    filters https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    filter https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    Cn https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    Gn https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    Sn https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    a https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    Tn https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    b https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    m https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    fn https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    na https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    rn https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    Zn https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    r https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    _dispatch https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    dispatch https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    dispatch https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    dispatch https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    u https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    o https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    a https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    graphQL https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    fetchHome https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    de https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    d https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    de https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    b https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    p https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    Pe https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    n https://abs.twimg.com/responsive-web/client-web/vendor.494acc9a.js:107
    dispatch https://abs.twimg.com/responsive-web/client-web/vendor.494acc9a.js:107
    Ee https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    n https://abs.twimg.com/responsive-web/client-web/vendor.494acc9a.js:107
    dispatch https://abs.twimg.com/responsive-web/client-web/vendor.494acc9a.js:107
    485142 https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    n https://abs.twimg.com/responsive-web/client-web/vendor.494acc9a.js:107
    485142 https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    485142 https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    promise callback*485142/</< https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    promise callback*485142/< https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    promise callback*485142 https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    l https://x.com/home:330
    promise callback*75787/< https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    promise callback*75787 https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
    l https://x.com/home:330
    <anonymous> https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:40
    O https://x.com/home:330
    <anonymous> https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:40
    n https://x.com/home:330
    <anonymous> https://abs.twimg.com/responsive-web/client-web/main.4ae4bd0a.js:1
3cb68114-b426-4c94-9cf6-2cd7eeab2f2e:408:26
`

**Comment by mone-stk** [comment]
Using Violent Monkey solved the problem.
