### ISSUE TITLE
导出喜欢标签页出现错误Cannot read properties of undefined (reading 'retweeted_status_result')

### ISSUE THREAD

**Issue by karasu10** [prinsss/twitter-web-exporter#47]
日志内容如下
#165 Cannot read properties of undefined (reading 'retweeted_status_result')
#164 Cannot read properties of undefined (reading 'retweeted_status_result')
#163 Cannot read properties of undefined (reading 'retweeted_status_result')
#162 Cannot read properties of undefined (reading 'retweeted_status_result')
#161 Likes: 20 items received
#160 TweetDetail: 9 items received
#159 TweetDetail: 11 items received
#158 Cannot read properties of undefined (reading 'retweeted_status_result')
#157 Cannot read properties of undefined (reading 'retweeted_status_result')
#156 Cannot read properties of undefined (reading 'retweeted_status_result')

确认捕获范围推文已正常加载，出现这个错误是否受twitter的api调用次数限制？出现该错误前约导出了2k条数据。

**Comment by qingchunnh** [comment]
普通用户每天800条推文用完的话，浏览器控制台会报429的

**Comment by prinsss** [comment]
此问题应该已在 [v1.2.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.2.0) 版本中修复。如有问题请继续反馈。:)

**Comment by karasu10** [comment]
> 此问题应该已在 [v1.2.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.2.0) 版本中修复。如有问题请继续反馈。:)

该问题今天尝试了下没有复现，发现另一个问题：在加载大约1w8条数据后，日志行有正常输出 Likes: 20 items received，但是捕获数没办法即时更新同步，按钮弹出的窗口内也一样没办法同步数据，确认所有推文正常加载，devtool内看网络这边也没有接口报错，console里也没有特殊报错信息，初步怀疑是twitter本身的内存泄露问题导致了页面占用内存过高造成的，出现这个问题时页面内存占用已超过2G。很想吐槽一点：就算是虚拟列表的形式渲染也还是出现内存泄露，又不做传统分页真不知道他们怎么考虑的。

**Comment by prinsss** [comment]
@karasu10 在加载 1w8 条数据后，继续滚动页面，Twitter 自身还能继续显示新推文吗？是只有脚本不再继续捕获了吗？

现在脚本的设置页面里有个「本地数据库 > 统计」按钮，可以看下输出 `Likes: 20 items received` 前后统计的 `tweets` 和 `captures` 表长度是否有变化。

**Comment by karasu10** [comment]
> @karasu10 在加载 1w8 条数据后，继续滚动页面，Twitter 自身还能继续显示新推文吗？是只有脚本不再继续捕获了吗？
> 
> 现在脚本的设置页面里有个「本地数据库 > 统计」按钮，可以看下输出 `Likes: 20 items received` 前后统计的 `tweets` 和 `captures` 表长度是否有变化。

可以正常显示新的推文，捕获也有在继续，只不过想到导出时需要先放置一段时间（未统计）等油猴响应，才能加载出捕获的数据。
我现在正在做导出操作，等这批数据处理完后我看一下表长度是否正常变化。

**Comment by prinsss** [comment]
> 只不过想要导出时需要先放置一段时间（未统计）等油猴响应，才能加载出捕获的数据

哈哈，那这应该是脚本的问题……之前实现的时候偷懒了，从数据库里读取数据的时候是全量的，读一万多条那得卡一段时间。这个后面我优化下。可以试试设置页面里的「本地数据库 > 导出」按钮，那个有做分块导出处理，应该会不会那么卡。

> 日志行有正常输出 Likes: 20 items received，但是捕获数没办法即时更新同步

没法即时更新同步是指面板上的「已捕获: XXX」的数字没有更新吗？可以通过统计按钮，看看表长度是否有变化。

> 尝试过关闭油猴做对照，监控了页面内存的变化

意思是关闭油猴脚本后，就不会出现页面内存泄漏问题吗？

**Comment by karasu10** [comment]
> > 只不过想要导出时需要先放置一段时间（未统计）等油猴响应，才能加载出捕获的数据
> 
> 哈哈，那这应该是脚本的问题……之前实现的时候偷懒了，从数据库里读取数据的时候是全量的，读一万多条那得卡一段时间。这个后面我优化下。可以试试设置页面里的「本地数据库 > 导出」按钮，那个有做分块导出处理，应该会不会那么卡。
> 
> > 日志行有正常输出 Likes: 20 items received，但是捕获数没办法即时更新同步
> 
> 没法即时更新同步是指面板上的「已捕获: XXX」的数字没有更新吗？可以通过统计按钮，看看表长度是否有变化。
> 
> > 尝试过关闭油猴做对照，监控了页面内存的变化
> 
> 意思是关闭油猴脚本后，就不会出现页面内存泄漏问题吗？

本地数据库导出的这个我后面再尝试一下。
面板上[已捕获：XXX]的数字没有更新，并且点击按钮打开的面板内也没有捕获的推文数据。
内存泄露这边不是的，即时是未开启油猴的情况下，我甚至把其他一些如假名标识，推特布局优化的插件也全部关掉；去加载这个数据量也一样会出现内存泄露。

**Comment by karasu10** [comment]
表长度经测试是有正常变化的，统计显示已捕获的推文数是21712，本地数据库导出了3个148M的JSON文件，没想到扔VScode里面已经因为文件过大不支持格式化了。

**Comment by prinsss** [comment]
感觉可能是数据库太大导致用于实时更新 UI 上已捕获数量的 [liveQuery](https://dexie.org/docs/liveQuery()) 订阅出了问题，我也没试过在浏览器里存这么多数据……点统计按钮能触发 UI 更新的话，可以当作临时解决方案。

> 即使是未开启油猴的情况下，[...] 去加载这个数据量也一样会出现内存泄露

那看来是 Twitter 网页自身有问题了😂

**Comment by prinsss** [comment]
这个 issue 我先关闭了，后续如果有其他关于数据库和导出的问题，可以新开一个 issue。:)
