### ISSUE TITLE
导出关注列表出现一系列Cannot read properties of undefined问题

### ISSUE THREAD

**Issue by Closure-arknights** [prinsss/twitter-web-exporter#48]
我在查看抓取的关注页面时一旦切到某几个用户名还是别的什么有特殊字符（我猜就是特殊字符）的那一页就报红，自然导出功能进度条也会卡在那个用户名之前，我尝试了v1.1.0 和 v1.0.10都会报红

#10 Cannot read properties of undefined (reading 'screen_name')
#9 Cannot read properties of undefined (reading 'created_at')
#8 Cannot read properties of undefined (reading 'description')
#7 Cannot read properties of undefined (reading 'screen_name')

![image](https://github.com/user-attachments/assets/65033a9c-a85e-4bb9-a8cc-6333ef7f8a45)

导出进度卡在第202条，这是我关注列表的第202 204条
![image](https://github.com/user-attachments/assets/97c83532-7d4e-4795-bb27-ad9252e9543a)
大佬可以看看，因为这个没办法继续导出了

**Comment by qingchunnh** [comment]
尝试使用[1.2.0-alpha.4](https://github.com/prinsss/twitter-web-exporter/releases/tag/nightly)版本

**Comment by prinsss** [comment]
此问题已在 [v1.2.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.2.0) 版本中修复。如有问题，欢迎继续反馈。:)
