### ISSUE TITLE
数据量大导出时会到一定数量时静止无法导出了

### ISSUE THREAD

**Issue by smilesgitgood** [prinsss/twitter-web-exporter#49]
比如我导出7000数据，就会卡在5000多或者3000多静止不动了

**Comment by prinsss** [comment]
静止不动是指什么意思呢，是整个页面卡住，还是脚本不再接收新数据了？

这个问题可能已经修复，请尝试使用 [v1.2.0](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.2.0) 版本。

**Comment by smilesgitgood** [comment]
1.2已经修复了 谢谢。大神可以出个导入需要取消关注或者关注的ID后，能够自动进行取消关注的功能吗

**Comment by prinsss** [comment]
> 可以出个导入需要取消关注或者关注的ID后，能够自动进行取消关注的功能吗

目前此脚本没有添加自动化操作的计划。

你可以试试现有的移除关注工具，比如 [twitter-mass-unfollow](https://github.com/luqmanoop/twitter-mass-unfollow) 或 [unfollow.js](https://gist.github.com/JamieMason/7580315)。

**Comment by smilesgitgood** [comment]
好的 谢谢大神
