### ISSUE TITLE
增加个账户上次活跃时间功能可以清理僵尸账号

### ISSUE THREAD

**Issue by smilesgitgood** [prinsss/twitter-web-exporter#50]
https://chromewebstore.google.com/detail/x-unfollower-twitter-unfo/llepohldkecfbjemolgkdoinkihejmcp
感觉这个插件的调取活跃时间功能很好用 大神能不能在导出数据中加入活跃时间元数据一下呢，谢谢。

**Comment by prinsss** [comment]
这个功能无法实现。

我看了一下，X Unfollower 会主动调用 Twitter [v1.1 API](https://developer.x.com/en/docs/x-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-friends-list) 获取关注信息，并使用其中包含的 `status` 字段（最新推文）作为上次活跃时间展示。但是本脚本依赖的 GraphQL API 没有返回这个字段，所以没办法拿到这个信息。

**Comment by smilesgitgood** [comment]
> 这个功能无法实现。
> 
> 我看了一下，X Unfollower 会主动调用 Twitter [v1.1 API](https://developer.x.com/en/docs/x-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-friends-list) 获取关注信息，并使用其中包含的 `status` 字段（最新推文）作为上次活跃时间展示。但是本脚本依赖的 GraphQL API 没有返回这个字段，所以没办法拿到这个信息。

大神，这个插件下面的 accounts to unfollow 列出的账户列表 我想复制粘贴到excel上，复制后只能粘贴出少部分，有什么办法解决吗，谢谢。

**Comment by prinsss** [comment]
这我就不太清楚了，毕竟也不是我开发的插件。可以尝试联系下那个插件的作者，Chrome 商店页面上有邮箱。
