### ISSUE TITLE
导出时能增加一个tweet url的 列吧

### ISSUE THREAD

**Issue by cc0cc0cc0** [prinsss/twitter-web-exporter#6]
感觉可以找到原始的推文挺有用的。

**Comment by prinsss** [comment]
Hi，谢谢你的建议！

我记得之前好像添加过推文 URL 的显示，但是刚才看了下确实没有，应该是忘了……我下个版本加上吧。

另外，目前所有的导出格式中都包含了推文的 `id` 字段，你也可以根据 ID 直接访问对应的推文。比如一条 ID 是 `1767900771427791282` 的推文，就可以使用以下链接查看：

[https://twitter.com/i/status/1767900771427791282](https://twitter.com/i/status/1767900771427791282)

**Comment by cc0cc0cc0** [comment]
嗯，这个是自己推文是这样得，书签的格式可能不太一样了，如果方便的话，加上更好用。 用这个工具把之前的推文，bookmark，还有like都备份了。谢谢了。

**Comment by prinsss** [comment]
[v1.0.9](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.0.9) 已更新。
