### ISSUE TITLE
开启插件后刷不出帖子

### ISSUE THREAD

**Issue by wangnan789** [prinsss/twitter-web-exporter#8]
如题
开启插件后刷不出帖子,我只装了一个插件.不启用插件又可以刷出帖子
![1](https://github.com/prinsss/twitter-web-exporter/assets/22336739/023e42fc-6204-4669-8d26-32d29a2cc9f0)

![2](https://github.com/prinsss/twitter-web-exporter/assets/22336739/2ab4689f-b293-498b-9ca8-d04b8dcf9692)

**Comment by prinsss** [comment]
Hi,

感谢反馈。为了帮助排查问题，麻烦提供以下信息：

1. 你的浏览器版本
2. 你的脚本管理器版本（Tampermonkey/Violentmonkey 版本）
3. 你使用的 twitter-web-exporter 的版本

关于日期格式，这个格式是 API 返回的，目前没做处理。新版本可以考虑加个自定义格式的选项。

关于刷出好多条数据但又消失这个问题，你是有刷新了页面吗？

**Comment by wangnan789** [comment]
> Hi,
> 
> 感谢反馈。为了帮助排查问题，麻烦提供以下信息：
> 
>     1. 你的浏览器版本
> 
>     2. 你的脚本管理器版本（Tampermonkey/Violentmonkey 版本）
> 
>     3. 你使用的 twitter-web-exporter 的版本
> 
> 
> 关于日期格式，这个格式是 API 返回的，目前没做处理。新版本可以考虑加个自定义格式的选项。
> 
> 关于刷出好多条数据但又消失这个问题，你是有刷新了页面吗？

firefox-esr  115.7
Tampermonkey 5.1.0(已卸载)
Violentmonkey 2.8.1(在使用)
Twitter Web Exporter 1.0.8
由于更换脚本管理器monkey,重启浏览器,后面就刷不出数据了

**Comment by prinsss** [comment]
我看了一下，这可能是 Firefox 上的脚本 CSP 导致的问题：https://github.com/violentmonkey/violentmonkey/issues/1001

有时间可以试一下 Chrome 上有没有问题，Firefox 的兼容性问题我后面再看看。

**Comment by bxb100** [comment]
enable advanced mode
<img width="882" alt="image" src="https://github.com/prinsss/twitter-web-exporter/assets/20685961/0ba22987-43bf-4dc5-aa4b-6912c9404fd6">
scroll to bottom and enable `Add Tampermonkey to the HTML's CSP`

<img width="707" alt="image" src="https://github.com/prinsss/twitter-web-exporter/assets/20685961/51c3fe0d-844b-4d82-967b-c6045caff374">

**Comment by bxb100** [comment]
`Modify existing content security policy (CSP) headers: yes`
`Add Tampermonkey to the HTML's CSP: yes`

**Comment by wangnan789** [comment]
> 我看了一下，这可能是 Firefox 上的脚本 CSP 导致的问题：[violentmonkey/violentmonkey#1001](https://github.com/violentmonkey/violentmonkey/issues/1001)
> 
> 有时间可以试一下 Chrome 上有没有问题，Firefox 的兼容性问题我后面再看看。
在gnu/linux上chrome还不支持代理,不能安装扩展.暂时试不了

**Comment by prinsss** [comment]
@wangnan789 我试了下，上面 @bxb100 提到的配置在我这边是可以绕过 CSP 的（我的版本是 Firefox 115.9.1esr + Tampermonkey 5.1.0），可以在开启 TM 高级配置模式后如图设置：

![CleanShot 2024-04-08 at 00 29 28](https://github.com/prinsss/twitter-web-exporter/assets/11206497/0d9339e8-fba7-4837-bda4-1ddb8bb1302b)

**Comment by prinsss** [comment]
> "Fri Feb 09 16:21:55 +0000 2024" 这个日期格式能改成 "2024-03-28-4_16-01-50" 这样的格式吗?

[v1.0.9](https://github.com/prinsss/twitter-web-exporter/releases/tag/v1.0.9) 已支持，在 Settings 中将 Date Time Format 设置为 `YYYY-MM-DD_HH-mm-ss` 即可。

**Comment by prinsss** [comment]
此问题后续将集中到 https://github.com/prinsss/twitter-web-exporter/issues/19 讨论。
