### ISSUE TITLE
意义

### ISSUE THREAD

**Issue by m4ra7h0n** [prinsss/twitter-web-exporter#9]
如果不能自动全部导出，那么这个半成品的软件意义何在

**Comment by prinsss** [comment]
1. 市面上支持自动导出的服务底层使用的都是 Twitter 开发者 API，价格是 $5,000 每月起步，普通人无力承受。
2. 这个项目利用了 Web 版的 API，通过监听网络请求响应来获取数据。
3. 为了避免自动行为 (Botting) 可能导致的服务协议违反，本项目不提供自动服务，要求用户手动浏览网页来获取数据。
4. 这样可以最大程度避免封号的风险，而用户如果需要也可以自己配合 auto-scroll 等软件实现自动导出。

我这样解释，你可以理解吗？

**Comment by SiZapPaaiGwat** [comment]
😄，你这话说的。我觉得导出都没意义

**Comment by mundane799699** [comment]
要不你来写一个能够自动全部导出的吧

**Comment by prinsss** [comment]
Closing as off-topic now. Feel free to open new issues if you have any further questions. :)
